### ISSUE TITLE
current problems ive found in the project

### ISSUE THREAD

**Issue by arielveremeev** [arielveremeev/2DAppForge#6]
disconect button doesnt have full functionality
if login is done after disconect buttons dont reset(cant create session ecd)
need to fix select to only select if an inside of a shape is pressed(use distance from click coords to shape BB)
fix rectangle scale,rotate and send scale,rotate
rebind send scale and send rotate to left mouse button for convinience
fix rotate and scale, wrong shape is recived if the mode isnt "freshly" chosen
check selection in session list(even if the list itself is selected the buttons are updated)
check export file, not working idk why
**maybe make rectangle a polygon**

**Comment by BarabashkaD** [comment]
each problem should be separate issue for tracking the solving process

**Comment by BarabashkaD** [comment]
this list its just title
please in each ticket describe problem
for example "doesnt have full functionality" 
explain what is a full and what exactly missed
